stages:
  tagAndInspectDatabase:
    actions:
    - type: liquibase
      command: tag
      cmdArg: {tag: "GHA-TAG"}

    - type: liquibase
      command: status
      cmdArg:{verbose: true}

    - type: liquibase
      command: updatesql
      cmdArg: {}
      